# Generated by Django 5.0.6 on 2024-07-18 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 8, 26, 11, 841492)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=' ', max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='querry',
            field=models.TextField(default=' ', max_length=700),
        ),
    ]
